# Generated by Django 2.2.8 on 2020-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200126_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_books',
            field=models.ManyToManyField(related_name='owner', to='search.Book'),
        ),
    ]
