# Generated by Django 2.2.8 on 2020-01-16 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
