# Generated by Django 2.2.8 on 2020-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
