# Generated by Django 2.2.8 on 2020-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200126_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('Neuf', 'Neuf'), ('Bon état', 'Bon état'), ('Légèrement abimé', 'Légèrement abimé'), ('Très abimé', 'Très abimé')], max_length=50, null=True),
        ),
    ]
