name: Django CD on GCP instance

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    needs: set-env-vars
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: exelban/gcloud@master
        env:
          PROJECT_ID: bookswap-265316
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml cron.yaml